### PR TITLE
Adding shallow check for --single-quotes option

### PR DESCRIPTION
**Pull request by ewerybody**
I'm kinda fresh with these. Wurks for me tho.
Can someone please have a look? 🙂

### CODE REVIEW

**Comment by richardARPANET** [comment]
@ewerybody What effect does this change have?

**Comment by ewerybody** [comment]
Hello @richardARPANET. This
- adds checking `sys.args` for a `--single-quotes` argument. If found:
  - monkeypatches `black.normalize_string_quotes` with `brunette.normalize_string_quotes`
  - removes the `--single-quotes` argument again to keep the black-arg-parser happy

**Comment by richardARPANET** [comment]
You've just described the code, rather than its behavioural change. Does this fix a bug?

**Comment by ewerybody** [comment]
No. This is aimed to add the command line option `--single-quotes` so you don't need a config-file.

**Comment by ewerybody** [comment]
@richardARPANET Shouldn't we rather have `brunette` use single-quotes by default? And have it optionally fallback to double-quotes on demand? 🤔

**Comment by richardARPANET** [comment]
@ewerybody please could you fix the conflicts and add example usage to to the README. Then I'll test out and release this. Thanks

**Comment by ewerybody** [comment]
Alright. Since all the `click` stuff moved into here as well it became much more straightforward! 🌈

I wanted to throw together a test as well but .. I dunno how this would go as I have `brunette` in my Python-environment but want to test the dev-one 🤔.

**Comment by richardARPANET** [comment]
@ewerybody 

To test the dev one:

```bash
pip uninstall -y brunette
pip install -e .
```

(run from repo root folder)

**Comment by ewerybody** [comment]
OK neat! I was thinking about an on-the-fly-version. But yeah that helps :) thanks!
Let me cook a small test...

**Comment by ewerybody** [comment]
OK. I took the original test data just split it into proper source and target files.
I'm not so fond of the `subprocess` calling but that's what we're supporting here. So I hope it's fine?
What do you think?

**Comment by richardARPANET** [comment]
Thanks

**Pull request merged**
